version: '3.4'

services:
  keycloakwebapi:
    image: ${DOCKER_REGISTRY-}keycloakwebapi
    container_name: KeycloakWebAPI
    build:
      context: .
      dockerfile: Projects/AuthenticationAuthorization/Keycloak/KeycloakWebAPI/Dockerfile
    ports:
    - 5000:8080
    - 5001:8081

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: Keycloak
    command: start-dev
    environment:
    - KC_HEALTH_ENABLED=true
    - KEYCLOAK_ADMIN=admin
    - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
    - ./.containers/identity:/opt/keycloak/data
    ports:
    - 18080:8080