@HostAddress = https://localhost:7034

POST {{HostAddress}}/api/Files/GetFile
Accept: application/json
content-type: application/json

    {
        "fileGuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    }

###

GET {{HostAddress}}/Files
Accept: application/json

###
